# Use Travis's cointainer based infrastructure
sudo: false
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - /opt/chefdk/embedded/bin/chef gem install chef-sugar

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/bin/chef exec rake

before_install:
  - openssl aes-256-cbc -K $encrypted_863b80624658_key -iv $encrypted_863b80624658_iv -in supermarket.pem.enc -out supermarket.pem -d

deploy:
  provider: chef-supermarket
  edge: true
  user_id: redguide
  client_key: supermarket.pem
  cookbook_category: Operating Systems & Virtualization
  on:
    tags: true
    branch: master
